#!/bin/sh
### BEGIN INIT INFO
# Provides:          scull
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start SCULL module at boot
### END INIT INFO

case "$1" in
  start)
    echo "Loading scull module"
    modprobe scull
    ;;
  stop)
    echo "Unloading scull module"
    modprobe -r scull
    ;;
  *)
    echo "Usage: /etc/init.d/scull {start|stop}"
    exit 1
    ;;
esac

exit 0
